apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: teamcity-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        editor: vscode
        app: teamcity-server
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: teamcity-server-data
      - name: log
        persistentVolumeClaim:
          claimName: teamcity-server-logs
      containers:
      - name: teamcity-server
        image: jetbrains/teamcity-server:latest
        volumeMounts:
        - mountPath: "/data/teamcity_server/datadir"
          name: data
        - mountPath: "/opt/teamcity/logs"
          name: log
        ports:
        - name:  teamcity-server
          containerPort:  8111
---
kind: Service
apiVersion: v1
metadata:
  name:  teamcity-server
spec:
  selector:
    app: teamcity-server
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8111
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: teamcity-agent-warrior-01
spec:
  replicas: 1
  template:
    metadata:
      labels:
        editor: vscode
        app: teamcity-agent
    spec:
      securityContext:
        fsGroup: 412 # Group ID of docker group on k8s nodes.
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      containers:
      - name: teamcity-agent
        image: jetbrains/teamcity-agent:latest
        volumeMounts:
        - mountPath: "/var/run/docker.sock"
          name: dockersock
        env:
        - name: SERVER_URL
          value: "http://teamcity-server:80"
        - name: AGENT_NAME
          value: Warrior-01
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: teamcity-agent-warrior-02
spec:
  replicas: 1
  template:
    metadata:
      labels:
        editor: vscode
        app: teamcity-agent
    spec:
      securityContext:
        fsGroup: 412 # Group ID of docker group on k8s nodes.
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      containers:
      - name: teamcity-agent
        image: jetbrains/teamcity-agent:latest
        volumeMounts:
        - mountPath: "/var/run/docker.sock"
          name: dockersock
        env:
        - name: SERVER_URL
          value: "http://teamcity-server:80"
        - name: AGENT_NAME
          value: Warrior-02
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: teamcity-server-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: teamcity-server-logs
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 5Gi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: teamcity-dns
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: teamcity.c28bfbc3d7724623a46f.westeurope.aksapp.io
    http:
      paths:
      - backend:
          serviceName: teamcity-server
          servicePort: 80
        path: /
