apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-dns
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: kibana.c90b5ad23c6d4683a634.westeurope.aksapp.io
    http:
      paths:
      - backend:
          serviceName: kibana-logging
          servicePort: 5601
        path: /
